<?php

declare(strict_types = 1);

namespace Pekral\GoogleConsole\Enum;

enum IndexingCheckReasonCode: string
{

    case INDEXED_CONFIRMED = 'INDEXED_CONFIRMED';

    case NOT_INDEXED_CONFIRMED = 'NOT_INDEXED_CONFIRMED';

    case INDEXING_PENDING = 'INDEXING_PENDING';

    case SOFT_404_SUSPECTED = 'SOFT_404_SUSPECTED';

    case DUPLICATE_CANONICAL_OTHER = 'DUPLICATE_CANONICAL_OTHER';

    case DUPLICATE_WITHOUT_CANONICAL = 'DUPLICATE_WITHOUT_CANONICAL';

    case ROBOTS_BLOCKED = 'ROBOTS_BLOCKED';

    case META_NOINDEX = 'META_NOINDEX';

    case HTTP_STATUS_NOT_200 = 'HTTP_STATUS_NOT_200';

    case REDIRECTED = 'REDIRECTED';

    case CANONICAL_MISMATCH = 'CANONICAL_MISMATCH';

    case RATE_LIMITED = 'RATE_LIMITED';

    case AUTH_REQUIRED_OR_FAILED = 'AUTH_REQUIRED_OR_FAILED';

    case TIMEOUT = 'TIMEOUT';

    case CAPTCHA_OR_BLOCKED = 'CAPTCHA_OR_BLOCKED';

    case INSUFFICIENT_DATA = 'INSUFFICIENT_DATA';

    case HEURISTIC_ONLY = 'HEURISTIC_ONLY';

}
